name: Build-and-Test

on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]
   
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    # checkout all sources from git
    - name: Checkout Sources
      uses: actions/checkout@v2
    # install dotnet SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: 6.0.x
        
        
   
    
