name: Build-and-Test2
steps:
# checkout all sources from git
- name: Checkout Sources
  uses: actions/checkout@v2
# install dotnet SDK
- name: Setup .NET
  uses: actions/setup-dotnet@v1
  with:
    dotnet-version: 6.0.x
    
